




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace SocialGameC2C
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool ScribblePoint(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int groupID, UnityEngine.Vector3 point)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.ScribblePoint;
		__msg.Write(__msgid);
		SngClient.Marshaler.Write(__msg, groupID);
		SngClient.Marshaler.Write(__msg, point);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_ScribblePoint, Common.ScribblePoint);
}

public bool ScribblePoint(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int groupID, UnityEngine.Vector3 point)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.ScribblePoint;
__msg.Write(__msgid);
SngClient.Marshaler.Write(__msg, groupID);
SngClient.Marshaler.Write(__msg, point);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_ScribblePoint, Common.ScribblePoint);
}
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_ScribblePoint="ScribblePoint";
       
const string RmiName_First = RmiName_ScribblePoint;
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

