




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

namespace SocialGameC2S
{
	internal class Proxy:Nettention.Proud.RmiProxy
	{
public bool RequestLogon(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, String villeName, bool isNewVille)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestLogon;
		__msg.Write(__msgid);
		SngClient.Marshaler.Write(__msg, villeName);
		SngClient.Marshaler.Write(__msg, isNewVille);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestLogon, Common.RequestLogon);
}

public bool RequestLogon(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, String villeName, bool isNewVille)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestLogon;
__msg.Write(__msgid);
SngClient.Marshaler.Write(__msg, villeName);
SngClient.Marshaler.Write(__msg, isNewVille);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestLogon, Common.RequestLogon);
}
public bool RequestAddTree(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, UnityEngine.Vector3 position)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestAddTree;
		__msg.Write(__msgid);
		SngClient.Marshaler.Write(__msg, position);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestAddTree, Common.RequestAddTree);
}

public bool RequestAddTree(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, UnityEngine.Vector3 position)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestAddTree;
__msg.Write(__msgid);
SngClient.Marshaler.Write(__msg, position);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestAddTree, Common.RequestAddTree);
}
public bool RequestRemoveTree(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int treeID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.RequestRemoveTree;
		__msg.Write(__msgid);
		SngClient.Marshaler.Write(__msg, treeID);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_RequestRemoveTree, Common.RequestRemoveTree);
}

public bool RequestRemoveTree(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int treeID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.RequestRemoveTree;
__msg.Write(__msgid);
SngClient.Marshaler.Write(__msg, treeID);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_RequestRemoveTree, Common.RequestRemoveTree);
}
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_RequestLogon="RequestLogon";
const string RmiName_RequestAddTree="RequestAddTree";
const string RmiName_RequestRemoveTree="RequestRemoveTree";
       
const string RmiName_First = RmiName_RequestLogon;
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

